version: "3.7"
services: 
    wordpress:
      image: wordpress
      restart: always
      ports:
       - 8080:80
      environment: 
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_USER: usr1
       WORDPRESS_DB_PASSWORD: password
       WORDPRESS_DB_NAME: wpdb
      volumes:
       - ./wordpress:/var/www/html
    db:
      image: mysql:5.7
      restart: always
      environment: 
       MYSQL_DATABASE: wpdb
       MYSQL_USER: usr1
       MYSQL_PASSWORD: password
       MYSQL_RANDOM_ROOT_PASSWORD: '1'
      volumes: 
       - ./db:/var/lib/mysql